-- DO NOT run this file as one big script if you hit parse errors before.
-- Run these three files IN ORDER, each in a fresh SQL Editor query:
--
--   1) supabase/curriculum-01-table.sql
--   2) supabase/curriculum-02-policies.sql
--   3) supabase/curriculum-03-seed.sql
--
-- Each step must succeed before the next.
